# Generated by Django 4.2.7 on 2024-11-21 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manil_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Despatch_Details',
        ),
    ]
