# Generated by Django 5.1.1 on 2024-10-14 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manil_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='chai_point_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=100, unique=True)),
                ('first_name', models.CharField(max_length=30, null=True)),
                ('last_name', models.CharField(max_length=30, null=True)),
                ('role', models.CharField(max_length=50)),
                ('email_id', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=355, null=True)),
                ('pwd_date', models.DateTimeField(null=True)),
                ('reg_status', models.BooleanField(default=0)),
                ('creation_date', models.DateTimeField()),
                ('created_by', models.CharField(max_length=100)),
                ('deletion_date', models.DateTimeField(blank=True, null=True)),
                ('deleted_by', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
