# Generated by Django 5.1.1 on 2024-10-14 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manil_app', '0002_chai_point_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='manil_order',
            name='po_authority',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='manil_order',
            name='po_authority_date',
            field=models.DateField(null=True),
        ),
    ]
