# Generated by Django 4.2.7 on 2024-11-21 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manil_app', '0002_delete_despatch_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='Despatch_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('process_num', models.CharField(max_length=100)),
                ('process_date', models.DateTimeField()),
                ('client_id', models.CharField(max_length=100)),
                ('client_name', models.CharField(max_length=255)),
                ('order_number', models.CharField(max_length=100)),
                ('order_date', models.DateTimeField()),
                ('dispatch_date', models.DateTimeField()),
                ('dispatch_lr_num', models.CharField(max_length=100)),
                ('exp_del_dt', models.DateTimeField()),
                ('client_rec_dt', models.DateTimeField(null=True)),
                ('creation_date', models.DateTimeField()),
                ('created_by', models.CharField(max_length=100)),
                ('received_by', models.CharField(max_length=100, null=True)),
                ('received_date', models.DateTimeField(null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Dispatch_images',
        ),
        migrations.RenameField(
            model_name='remarkes_images',
            old_name='process_num',
            new_name='order_number',
        ),
    ]
