# Generated by Django 4.2.7 on 2024-11-22 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manil_app', '0003_despatch_details_delete_dispatch_images_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_tickets',
            name='process_num',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
