# Generated by Django 5.1.4 on 2025-01-07 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manil_app', '0003_notification_created_at_notification_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='client_order_details',
            name='total',
            field=models.BigIntegerField(default=1),
            preserve_default=False,
        ),
    ]
