# Generated by Django 5.1.4 on 2025-01-07 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manil_app', '0004_client_order_details_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='manil_order_details',
            name='total',
            field=models.BigIntegerField(default=1),
            preserve_default=False,
        ),
    ]
