# Generated by Django 5.1.4 on 2025-01-08 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manil_app', '0006_rename_total_client_order_details_total_base_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client_order_details',
            name='total_base',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='manil_order_details',
            name='total_base',
            field=models.BigIntegerField(null=True),
        ),
    ]
