# Generated by Django 5.1.4 on 2025-01-09 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manil_app', '0008_notification_order_number'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Notification',
            new_name='Manil_Notification',
        ),
    ]
