# Generated by Django 5.1.4 on 2025-01-10 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manil_app', '0010_chaipoint_notification_client_notification'),
    ]

    operations = [
        migrations.RenameField(
            model_name='remarkes_images',
            old_name='process_num',
            new_name='order_number',
        ),
    ]
