# Generated by Django 5.1.4 on 2025-01-10 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manil_app', '0011_rename_process_num_remarkes_images_order_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client_Inv_Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('message', models.TextField(blank=True, null=True)),
                ('is_read', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Inv_Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('message', models.TextField(blank=True, null=True)),
                ('is_read', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='chaipoint_notification',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='chaipoint_notification',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='client_notification',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='client_notification',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='manil_notification',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='manil_notification',
            name='created_by',
        ),
    ]
