# Generated by Django 5.1.4 on 2025-01-15 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manil_app', '0012_client_inv_notification_inv_notification_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order_Tickets_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_num', models.CharField(max_length=100)),
                ('material_name', models.CharField(max_length=255)),
                ('order_qty', models.CharField(max_length=10)),
                ('received_qty', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='order_tickets',
            name='remarks_type',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
