# Generated by Django 5.1.4 on 2025-01-16 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manil_app', '0014_rename_ticket_num_order_tickets_details_order_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_tickets_details',
            name='uom',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
    ]
