# Generated by Django 5.1.4 on 2025-01-16 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manil_app', '0016_alter_order_tickets_details_order_qty_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_tickets_details',
            name='order_qty',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='order_tickets_details',
            name='received_qty',
            field=models.BigIntegerField(),
        ),
    ]
