# Generated by Django 5.1.4 on 2025-01-16 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manil_app', '0017_alter_order_tickets_details_order_qty_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='manil_order',
            name='order_type',
            field=models.BooleanField(default=True),
        ),
    ]
