# Generated by Django 5.1.4 on 2025-01-18 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manil_app', '0018_manil_order_order_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Re_client_order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(max_length=100)),
                ('client_name', models.CharField(max_length=255)),
                ('order_number', models.CharField(max_length=100)),
                ('order_date', models.DateTimeField()),
                ('po_authority', models.CharField(max_length=255, null=True)),
                ('po_authority_date', models.DateField(null=True)),
                ('creation_date', models.DateTimeField()),
                ('created_by', models.CharField(max_length=100)),
                ('authorisation_date', models.DateTimeField(blank=True, null=True)),
                ('authorised_by', models.CharField(blank=True, max_length=100, null=True)),
                ('grand_total', models.BigIntegerField()),
                ('ammount_words', models.CharField(max_length=200)),
                ('shipping_address', models.TextField()),
                ('shipping_city', models.CharField(max_length=50, null=True)),
                ('shipping_state', models.CharField(max_length=50, null=True)),
                ('shipping_pin', models.BigIntegerField(null=True)),
                ('status', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Re_client_order_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=100)),
                ('material_name', models.CharField(max_length=255)),
                ('hsn_code', models.CharField(max_length=10)),
                ('uom', models.CharField(max_length=50)),
                ('qty', models.BigIntegerField()),
                ('base_price', models.BigIntegerField()),
                ('gst_type', models.CharField(max_length=50)),
                ('gst_rate', models.IntegerField()),
                ('gst_amt', models.BigIntegerField(null=True)),
                ('sub_total', models.BigIntegerField()),
                ('total_base', models.BigIntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Re_Despatch_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('process_num', models.CharField(max_length=100)),
                ('process_date', models.DateTimeField()),
                ('client_id', models.CharField(max_length=100)),
                ('client_name', models.CharField(max_length=255)),
                ('order_number', models.CharField(max_length=100)),
                ('order_date', models.DateTimeField()),
                ('dispatch_date', models.DateTimeField()),
                ('dispatch_lr_num', models.CharField(max_length=100)),
                ('exp_del_dt', models.DateTimeField()),
                ('client_rec_dt', models.DateTimeField(null=True)),
                ('creation_date', models.DateTimeField()),
                ('created_by', models.CharField(max_length=100)),
                ('received_by', models.CharField(max_length=100, null=True)),
                ('received_date', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Re_manil_order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('process_num', models.CharField(max_length=100)),
                ('client_id', models.CharField(max_length=100)),
                ('client_name', models.CharField(max_length=255)),
                ('order_number', models.CharField(max_length=100)),
                ('order_date', models.DateTimeField()),
                ('po_authority', models.CharField(max_length=255, null=True)),
                ('po_authority_date', models.DateField(null=True)),
                ('creation_date', models.DateTimeField()),
                ('created_by', models.CharField(max_length=100)),
                ('authorisation_date', models.DateTimeField(blank=True, null=True)),
                ('authorised_by', models.CharField(blank=True, max_length=100, null=True)),
                ('grand_total', models.BigIntegerField()),
                ('ammount_words', models.CharField(max_length=200)),
                ('shipping_address', models.TextField()),
                ('shipping_city', models.CharField(max_length=50, null=True)),
                ('shipping_state', models.CharField(max_length=50, null=True)),
                ('shipping_pin', models.BigIntegerField(null=True)),
                ('status', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Re_manil_order_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('process_num', models.CharField(max_length=100)),
                ('material_name', models.CharField(max_length=255)),
                ('hsn_code', models.CharField(max_length=10)),
                ('uom', models.CharField(max_length=50)),
                ('qty', models.BigIntegerField()),
                ('base_price', models.BigIntegerField()),
                ('gst_type', models.CharField(max_length=50)),
                ('gst_rate', models.IntegerField()),
                ('gst_amt', models.BigIntegerField(null=True)),
                ('sub_total', models.BigIntegerField()),
                ('total_base', models.BigIntegerField(null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='manil_order',
            name='order_type',
        ),
    ]
