# Generated by Django 5.1.4 on 2025-01-18 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manil_app', '0019_re_client_order_re_client_order_details_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='re_manil_order',
            name='re_order_number',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
