# Generated by Django 5.1.4 on 2025-01-18 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manil_app', '0020_re_manil_order_re_order_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='re_manil_order',
            name='ticket_num',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
