# Generated by Django 4.2.7 on 2025-01-25 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manil_app', '0021_re_manil_order_ticket_num'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client_Ticket_Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_num', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('message', models.TextField(blank=True, null=True)),
                ('is_read', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket_Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_num', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('message', models.TextField(blank=True, null=True)),
                ('is_read', models.BooleanField(default=False)),
            ],
        ),
    ]
